spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ps
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    properties:
      show-sql: true
      format-sql: true 
    hibernate:
      ddl-auto: update
  flyway:
    baseline-on-migrate: true
#  sql:
#    init:
#      mode: ALWAYS

server:
  error:
    include-binding-errors: never
    include-message: always
    include-stacktrace: never